# Generated by Django 6.0 on 2025-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar na Página Inicial'),
        ),
    ]
