# Generated by Django 6.0 on 2025-12-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Casa', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='reference_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=9),
        ),
    ]
