# Generated by Django 6.0 on 2025-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_address_district_address_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_requests/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Destaque na Home'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Foto principal?'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=20),
        ),
    ]
