# Generated by Django 6.0 on 2026-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_faq_sitesettings_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
