# Generated by Django 6.0 on 2026-03-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_selected_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contato@loja.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_pdf',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#D4AF37', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
